language: objective-c
osx_image: xcode8.2
script: 
  - xcodebuild -workspace SZMentions.xcworkspace -scheme SZMentionsSwift CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'SZMentionsSwift'
